name: Build
on:
  workflow_dispatch:
  push:
    branches: "**"
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ released ]
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: "checkout git repository"
        uses: actions/checkout@v6
      - name: "setup bun"
        uses: oven-sh/setup-bun@v2
      - name: "install bun dependencies"
        run: cd web && bun install
      - name: "lint frontend"
        run: cd web && bun run lint
      - name: "setup jdk"
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: "setup gradle"
        uses: gradle/actions/setup-gradle@v6
        # gradle-build-action doesn't support caching files in the project dir
      - name: "cache project local caches"
        uses: actions/cache@v5
        with:
          path: |
            .gradle/loom-cache
            fabric/.gradle/loom-cache
            paper/.gradle/caches/paperweight
            common/build/moddev
            neoforge/build/moddev
            sponge/build/moddev
          key: ${{ runner.os }}-project-local-gradle-caches-${{ hashFiles('**/libs.versions.toml', '**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-project-local-gradle-caches-
      - name: "execute gradle build"
        run: ./gradlew build
      - name: "determine status"
        run: |
          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
      - name: "upload artifacts"
        uses: actions/upload-artifact@v7
        with:
            name: artifacts
            path: "build/libs/*.jar"
